### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by tangyuanw** [infinite0522/Recurrent-ConFormer-for-WiFi-HAR#1]
dear authors, the evaluation module does not seem to provide code models.

**Comment by infinite0522** [comment]
The model can be easily trained using the provided code. You can replace the model path in the evaluation module with the path to your own trained model for testing purposes.
test: https://github.com/infinite0522/Recurrent-ConFormer-for-WiFi-HAR/blob/main/test.py
inference: https://github.com/infinite0522/Recurrent-ConFormer-for-WiFi-HAR/blob/main/inference.py
